server.port=8040
logging.level.org.springframework.boot.autoconfigure=DEBUG

# Expose all actuator web endpoints over HTTP
management.endpoints.web.exposure.include=*

# Optional: If you want to expose all JMX endpoints too
management.endpoints.jmx.exposure.include=*

spring.boot.admin.client.url=http://localhost:9000
# Give the client a clean display name for the UI dashboard
spring.application.name=Spring-Boot TF AutoConfig